# Generated by Django 5.0 on 2023-12-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udenews', '0002_news_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='desc',
        ),
        migrations.AddField(
            model_name='news',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
