# Generated by Django 5.0 on 2023-12-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udenews', '0003_remove_news_desc_news_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
