# Generated by Django 4.2.9 on 2024-01-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udenews', '0004_alter_news_date_alter_news_img_alter_news_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
