# Generated by Django 4.2.9 on 2024-01-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udenews', '0005_alter_news_date_alter_news_img_alter_news_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Imagen'),
        ),
    ]
